customCommands:
  - key: "a"
    command: "git add ."
    context: "files"
    description: "Add all files"
    loadingText: "Adding all files"
    subprocess: true
  - key: "c"
    command: "git cz"
    context: "files"
    description: "Commit with commitizen"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "r"
    command: "git rebase -i --root"
    context: "files"
    description: "Rebase from root"
    loadingText: "Opening rebase tool"
    subprocess: true
  - key: "p"
    command: "git push --force"
    context: "files"
    description: "Push to remote"
    loadingText: "Pushing to remote"
    subprocess: true
